In [4]:
from numpy import mat, zeros, shape, random, array, zeros_like, dot, linalg
from random import sample
import json
from math import pi, sqrt, exp, pow

In [1]:
cent2=[[2.515657568629142, 0.012148642249462209], [-0.5366231121915682, 2.6151608380095324], [6.017971546486905, 7.132784550067225]]

In [2]:
cent2

[[2.515657568629142, 0.012148642249462209],
 [-0.5366231121915682, 2.6151608380095324],
 [6.017971546486905, 7.132784550067225]]

In [10]:
mean = array(cent2[0])
mean

array([ 2.51565757,  0.01214864])

In [12]:
for i in range(1,3):
    print 'before',mean
    mean = mean + array(cent2[i])
    print mean
mean = mean/float(3)
mean

before [ 2.66566867  3.25336468]
[ 2.12904556  5.86852551]
before [ 2.12904556  5.86852551]
[  8.1470171   13.00131006]


array([ 2.71567237,  4.33377002])

In [22]:
cov = zeros((len(mean),len(mean)),dtype=float)
print 'Initial cov',cov
for x in cent2:
    print 'x',x
    print 'array',array(x)
    xmm = array(x) - mean
    print 'xmm',xmm
    print 'xmmsq',xmm[0]*xmm[0]
    for i in range(len(mean)):
        cov[i,i] = cov[i,i] + xmm[i]*xmm[i]

Initial cov [[ 0.  0.]
 [ 0.  0.]]
x [2.515657568629142, 0.012148642249462209]
array [ 2.51565757  0.01214864]
xmm [-0.2000148  -4.32162138]
xmmsq 0.0400059196923
x [-0.5366231121915682, 2.6151608380095324]
array [-0.53662311  2.61516084]
xmm [-3.25229548 -1.71860918]
xmmsq 10.577425886
x [6.017971546486905, 7.132784550067225]
array [ 6.01797155  7.13278455]
xmm [ 3.30229918  2.79901453]
xmmsq 10.9051798688


In [23]:
cov

array([[ 21.52261167,   0.        ],
       [  0.        ,  29.4645112 ]])

In [24]:
cov = cov/(float(3))
print cov
covInv = linalg.inv(cov)
print covInv

[[ 7.17420389  0.        ]
 [ 0.          9.82150373]]
[[ 0.13938829  0.        ]
 [ 0.          0.1018174 ]]


In [25]:
cov_1 = [covInv.tolist()]*3
print cov_1

[[[0.13938828825121014, 0.0], [0.0, 0.1018174026144369]], [[0.13938828825121014, 0.0], [0.0, 0.1018174026144369]], [[0.13938828825121014, 0.0], [0.0, 0.1018174026144369]]]


In [ ]:

fileOut = open(,'w')